apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo
          image: REPO/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 9091  # ✅ aligné
          readinessProbe:
            httpGet:
              path: /              # adapte si besoin (ex: /actuator/health)
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
