apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: NodePort        # garde NodePort si tu veux y accéder depuis ton LAN
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: 9091  # ✅ aligné avec l’app
